#$test($status = 0)

var a = $false
try {
	throw new Error("hello")
} catch($e : Error) {
    assert $? == 0
	$a = $true
	assert($e.message() == 'hello')
}
assert($a)

try {
	throw new OutOfRangeError("a")
} catch($e : Error) {
	assert($e is OutOfRangeError)
	assert($e.message() == "a")
}

try {
    $true ? throw new InvalidOperationError('34') : 54
} catch($e : SystemError) {
    assert($false)
} catch($e : OutOfRangeError) {
    assert($false)
} catch($e) {
    assert $e is Error
    assert($e is InvalidOperationError)
    assert(($e as InvalidOperationError).message() == '34')
}